In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]

In [8]:
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [9]:
dependent=dataset[['charges']]

In [10]:
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [13]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid = {'kernel':["linear","rbf","poly","sigmoid"],
'C':[10,100,1000,2000],
'gamma':["scale","auto"]}
grid = GridSearchCV(SVR(), param_grid, refit = True, verbose = 3,n_jobs=-1)
grid.fit(x_train,y_train)

Fitting 5 folds for each of 32 candidates, totalling 160 fits

C:\Users\user\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000], 'gamma': ['scale', 'auto'],
                         'kernel': ['linear', 'rbf', 'poly', 'sigmoid']},
             verbose=3)

In [14]:
re=grid.cv_results_
grid_predictions = grid.predict(x_test)

In [15]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,grid_predictions)
print("The R_score value for best parameter {}:".format(grid.best_params_),r_score)

The R_score value for best parameter {'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}: 0.860557928865969

In [16]:
table=pd.DataFrame.from_dict(re)

In [17]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.084401,0.007657,0.018756,6.251621e-03,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.377969,0.479601,0.317872,0.337979,0.324422,0.367569,0.059777,19
1,0.118787,0.032185,0.046889,1.711999e-02,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",0.004126,0.013244,-0.103775,-0.095165,-0.101602,-0.056634,0.053486,30
2,0.112535,0.028651,0.009377,7.656563e-03,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",0.054964,0.071297,-0.046513,-0.024157,-0.049652,0.001188,0.051594,25
3,0.112533,0.018228,0.015630,1.211955e-06,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.049644,0.076323,-0.046798,-0.040824,-0.046521,-0.001635,0.053474,27
4,0.084401,0.012504,0.012504,6.252074e-03,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.377969,0.479601,0.317872,0.337979,0.324422,0.367569,0.059777,19
5,0.100032,0.015941,0.043763,1.169606e-02,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",0.004055,0.013366,-0.103821,-0.095119,-0.101604,-0.056625,0.053504,29
6,0.100031,0.012503,0.015630,1.716614e-06,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",0.056274,0.069532,-0.045601,-0.025079,-0.049592,0.001107,0.051309,26
7,0.103156,0.021202,0.015630,8.064048e-07,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.049905,0.075905,-0.046585,-0.041004,-0.046507,-0.001657,0.053391,28
8,0.100031,0.021201,0.015630,1.101896e-06,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.584474,0.655818,0.553380,0.576939,0.546881,0.583498,0.038787,13
9,0.106282,0.015314,0.046890,1.712164e-02,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",0.301041,0.338741,0.174086,0.217641,0.183403,0.242982,0.065542,24
10,0.084506,0.012452,0.012505,6.252313e-03,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",0.537117,0.579373,0.471840,0.537966,0.424478,0.510155,0.054955,16
11,0.115651,0.015785,0.021881,7.657614e-03,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.478930,0.563200,0.427152,0.451250,0.432199,0.470546,0.049762,17
12,0.093554,0.016714,0.015630,3.162980e-07,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.584474,0.655818,0.553380,0.576939,0.546881,0.583498,0.038787,13
13,0.103158,0.015940,0.043763,1.169562e-02,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",0.300573,0.339474,0.173708,0.217991,0.183375,0.243024,0.065733,23
14,0.097535,0.022053,0.018133,5.004954e-03,100,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",0.540643,0.575051,0.474839,0.535730,0.424640,0.510181,0.053582,15
15,0.109426,0.013980,0.015631,1.070497e-06,100,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.478364,0.561673,0.428331,0.450454,0.431701,0.470105,0.049110,18
16,0.115038,0.025196,0.012504,6.252194e-03,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.605304,0.588725,0.623230,0.537931,0.616726,0.594383,0.030560,11
17,0.133824,0.024229,0.036774,4.186625e-03,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.733334,0.745892,0.687037,0.717769,0.649174,0.706641,0.034825,7
18,0.149926,0.031657,0.015628,2.565189e-06,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",0.828213,0.802622,0.799348,0.800587,0.735555,0.793265,0.030757,4
19,0.118784,0.012506,0.015629,1.228723e-06,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",0.400044,0.366097,0.242217,0.288461,0.351407,0.329645,0.056742,21
20,0.118968,0.012568,0.012606,6.305984e-03,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.605304,0.588725,0.623230,0.537931,0.616726,0.594383,0.030560,11
21,0.125436,0.013980,0.053142,7.657342e-03,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",0.733044,0.746232,0.686773,0.717920,0.649158,0.706625,0.034902,8
22,0.118766,0.018785,0.021882,7.658159e-03,1000,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",0.829631,0.802622,0.799620,0.800321,0.735580,0.793555,0.031072,3
23,0.137541,0.011696,0.021883,7.656933e-03,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.296082,0.372281,0.216401,0.291265,0.351325,0.305471,0.054387,22
24,0.168801,0.011696,0.018756,6.252456e-03,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",0.605277,0.583646,0.697368,0.532547,0.681425,0.620053,0.061555,9
25,0.159424,0.011697,0.056268,7.656758e-03,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",0.814295,0.780971,0.794227,0.793983,0.733663,0.783428,0.027068,5
26,0.217006,0.019600,0.018754,6.252050e-03,2000,scale,poly,"{'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}",0.845581,0.805624,0.816612,0.805133,0.754962,0.805582,0.029272,1
27,0.148893,0.007556,0.028792,4.935575e-03,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",-0.385658,-0.537098,-0.474912,-0.477335,-0.111187,-0.397238,0.150976,31
28,0.160739,0.015129,0.018756,6.252098e-03,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",0.605277,0.583646,0.697368,0.532547,0.681425,0.620053,0.061555,9
29,0.156298,0.009885,0.059393,1.169677e-02,2000,auto,rbf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}",0.814076,0.781092,0.794081,0.794075,0.733656,0.783396,0.027014,6
30,0.225070,0.023393,0.018756,6.252599e-03,2000,auto,poly,"{'C': 2000, 'gamma': 'auto', 'kernel': 'poly'}",0.845403,0.805639,0.816733,0.805143,0.754961,0.805576,0.029233,2
31,0.134417,0.007657,0.025008,7.655687e-03,2000,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.401855,-0.508082,-0.452827,-0.751013,-0.111859,-0.445127,0.205197,32