In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]

In [8]:
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [9]:
dependent=dataset[['charges']]

In [10]:
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
independent=sc.fit_transform(independent)

In [12]:
from sklearn.svm import SVR

In [13]:
from sklearn.model_selection import GridSearchCV
param_grid={'kernel':["linear","rbf","poly","sigmoid"],
'C':[10,100,1000,2000],'gamma':["auto","scale"]}
grid=GridSearchCV(SVR(),param_grid,refit=True,cv=5,verbose=3,n_jobs=-1)
grid.fit(independent,dependent)

Fitting 5 folds for each of 32 candidates, totalling 160 fits

C:\Users\user\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(cv=5, estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000], 'gamma': ['auto', 'scale'],
                         'kernel': ['linear', 'rbf', 'poly', 'sigmoid']},
             verbose=3)

In [14]:
re=grid.cv_results_
grid_predictions = grid.predict(independent)
from sklearn.metrics import r2_score
r_score=r2_score(dependent,grid_predictions)
print("The R_score value for best parameter {}:".format(grid.best_params_),r_score)

The R_score value for best parameter {'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}: 0.827481547165314

In [15]:
table=pd.DataFrame.from_dict(re)

In [16]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.168802,0.011696,0.018756,0.006253,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.487873,0.472341,0.485102,0.475835,0.447692,0.473769,0.014239,19
1,0.229688,0.058060,0.078579,0.008803,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",-0.050402,-0.045276,-0.016737,-0.041345,-0.048491,-0.040450,0.012248,30
2,0.178775,0.042406,0.033004,0.016178,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",0.037227,0.042884,0.065672,0.041406,0.034393,0.044316,0.011093,26
3,0.212653,0.018469,0.031490,0.009525,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.029301,0.043379,0.060402,0.040689,0.017824,0.038319,0.014285,27
4,0.184527,0.034044,0.023236,0.007003,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.487873,0.472341,0.485102,0.475835,0.447692,0.473769,0.014239,19
5,0.211205,0.030194,0.081154,0.015344,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",-0.050517,-0.045096,-0.016601,-0.041415,-0.048600,-0.040446,0.012321,29
6,0.193166,0.021300,0.025009,0.007656,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",0.039041,0.040111,0.063362,0.042506,0.036594,0.044323,0.009707,25
7,0.212565,0.036454,0.037512,0.012504,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.029716,0.042770,0.059852,0.040918,0.018234,0.038298,0.013912,28
8,0.178180,0.027251,0.021882,0.007658,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.641464,0.601994,0.627339,0.628877,0.596234,0.619182,0.017199,15
9,0.187559,0.032785,0.089132,0.024355,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",0.360724,0.347206,0.361437,0.343682,0.333290,0.349268,0.010678,21
10,0.195920,0.039306,0.033033,0.008002,100,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",0.650669,0.616836,0.642137,0.615462,0.606497,0.626320,0.016993,13
11,0.221687,0.040163,0.040637,0.012504,100,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.531459,0.492180,0.518726,0.511646,0.486503,0.508103,0.016679,17
12,0.202434,0.033533,0.031026,0.009896,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.641464,0.601994,0.627339,0.628877,0.596234,0.619182,0.017199,15
13,0.204859,0.050387,0.090914,0.012117,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",0.360068,0.348158,0.362312,0.343255,0.332521,0.349263,0.010997,22
14,0.198082,0.032229,0.031771,0.012843,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",0.654011,0.612976,0.636708,0.617573,0.608877,0.626029,0.016930,14
15,0.238628,0.050721,0.044608,0.006747,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.527367,0.490754,0.520064,0.511215,0.485494,0.506979,0.016308,18
16,0.266804,0.011696,0.040638,0.007657,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.672679,0.620927,0.730011,0.632260,0.691909,0.669557,0.039799,9
17,0.275924,0.006314,0.120287,0.013473,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",0.833468,0.754793,0.802307,0.777257,0.783844,0.790334,0.026383,8
18,0.301217,0.035174,0.037915,0.008175,1000,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",0.848655,0.774485,0.868188,0.805521,0.808550,0.821080,0.033316,4
19,0.298279,0.006061,0.051611,0.006299,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.170988,-0.021689,0.135578,0.120185,0.099719,0.100956,0.065599,24
20,0.270762,0.015932,0.034386,0.006252,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.672679,0.620927,0.730011,0.632260,0.691909,0.669557,0.039799,9
21,0.269941,0.008467,0.119305,0.008137,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.833330,0.754986,0.802746,0.777131,0.783512,0.790341,0.026356,7
22,0.303746,0.020986,0.038885,0.007001,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",0.848927,0.774567,0.868177,0.805541,0.808535,0.821149,0.033334,3
23,0.284643,0.012659,0.050016,0.006252,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",0.161027,0.099347,0.157690,0.184345,0.077914,0.136065,0.040377,23
24,0.318977,0.012504,0.034544,0.006176,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",0.671545,0.618499,0.728708,0.627927,0.691027,0.667541,0.040702,11
25,0.291267,0.007626,0.115896,0.007627,2000,auto,rbf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}",0.863090,0.775949,0.848369,0.801411,0.812077,0.820179,0.031655,6
26,0.425447,0.135857,0.037512,0.007657,2000,auto,poly,"{'C': 2000, 'gamma': 'auto', 'kernel': 'poly'}",0.851467,0.773953,0.868926,0.807826,0.814939,0.823422,0.033525,2
27,0.281337,0.009885,0.053142,0.007658,2000,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-1.377095,-1.487236,-1.402559,-1.330143,-1.162566,-1.351920,0.107552,32
28,0.312835,0.009536,0.037293,0.007389,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",0.671545,0.618499,0.728708,0.627927,0.691027,0.667541,0.040702,11
29,0.290736,0.012498,0.128165,0.006252,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",0.863070,0.775993,0.848544,0.801377,0.812016,0.820200,0.031676,5
30,0.378244,0.048827,0.040636,0.007657,2000,scale,poly,"{'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}",0.851782,0.774049,0.868717,0.807810,0.815101,0.823492,0.033486,1
31,0.275086,0.007656,0.040642,0.007650,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",-1.075530,-1.732497,-1.358992,-1.172710,-1.199166,-1.307779,0.231079,31

In [17]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:32
BMI:37
Children:2
Sex Male 0 or 1:1
Smoker Yes 0 or 1:0

In [18]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[3974896.72040641]